# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'UnitTestingExamples' do

end

target 'UnitTestingExamplesTests' do
    pod 'Specta',   '~> 0.5'
    pod 'Expecta',  '~> 1.0.0'   # expecta matchers
    pod 'OCMock',   '~> 3.1'   # OCMock
end

